/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IF2A;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author user-hp
 */
public class FormUtama extends javax.swing.JFrame {
    private int a,b,h;
    int menu_utama, minuman, menu_ringan, menu_tambahan, total=0;
    
    Connection conn;
    Statement stmt;
    
    int jml=0;
    String makan="";
        
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();

    
    public void koneksi_db(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/kasir_kantin", "root", "");
            stmt=conn.createStatement();
            
            System.out.println("Koneksi berhasil");
        }catch (Exception e){
            System.out.println("Koneksi gagal : "+e);
        }
    }    
    /**
     * Creates new form FormUtama
     */
    
    public void tambah(String nama, int jml, int total){
        String sql = "insert into pembelian (nama_barang,jumlah,total,tanggal) values('"+nama+"','"+jml+"',"
                +"'"+total+"','"+dateFormat.format(date)+"')";
        try{
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data telah berhasil ditambahkan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,"error = "+e);
        }
    }
    
    public void clear(){
        TxtChicken_Fillet.setEnabled(false);
        TxtSotong_Tepung.setEnabled(false);
        TxtAyam_Rica_Rica.setEnabled(false);
        TxtAyam_Penyet.setEnabled(false);
        TxtTela_Tela.setEnabled(false);
        TxtKentang_Goreng.setEnabled(false);
        TxtKulit_Ayam.setEnabled(false);
        TxtGorengan.setEnabled(false);
        TxtSeblak.setEnabled(false);
        TxtSoto.setEnabled(false);
        TxtNasi_Goreng.setEnabled(false);
        TxtKwitiau.setEnabled(false);
        TxtTeh_Obeng.setEnabled(false);
        TxtLemon_Tea.setEnabled(false);
        TxtThai_Tea.setEnabled(false);
        TxtGreentea.setEnabled(false);
        
        
        TxtChicken_Fillet.setText("");
        Chicken_Fillet.setSelected(false);
        
        TxtSotong_Tepung.setText("");
        Sotong_Tepung.setSelected(false);
        
        TxtAyam_Rica_Rica.setText("");
        Ayam_Rica_Rica.setSelected(false);
        
        TxtAyam_Penyet.setText("");
        Ayam_Penyet.setSelected(false);
        
        TxtTela_Tela.setText("");
        Tela_Tela.setSelected(false);
        
        TxtKentang_Goreng.setText("");
        Kentang_Goreng.setSelected(false);
        
        TxtKulit_Ayam.setText("");
        Kulit_Ayam.setSelected(false);
        
        TxtGorengan.setText("");
        Gorengan.setSelected(false);
        
        TxtSeblak.setText("");
        Seblak.setSelected(false);
        
        TxtSoto.setText("");
        Soto.setSelected(false);
        
        TxtNasi_Goreng.setText("");
        Nasi_Goreng.setSelected(false);
        
        TxtKwitiau.setText("");
        Kwitiau.setSelected(false);
        
        TxtTeh_Obeng.setText("");
        Teh_Obeng.setSelected(false);
        
        TxtLemon_Tea.setText("");
        Lemon_Tea.setSelected(false);
        
        TxtThai_Tea.setText("");
        Thai_Tea.setSelected(false);
        
        TxtGreentea.setText("");
        Greentea.setSelected(false);
        
        totalharga.setText("");
        bayar.setText("");
        kembalian.setText("");
    }
    
    public FormUtama() {
        initComponents();
        koneksi_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background2 = new IF2A.Background();
        lkjhg = new IF2A.Background();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        totalharga = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B_Hapus = new javax.swing.JButton();
        B_Hitung = new javax.swing.JButton();
        hitungkem = new javax.swing.JButton();
        B_selesai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtAyam_Penyet = new javax.swing.JTextField();
        TxtAyam_Rica_Rica = new javax.swing.JTextField();
        TxtChicken_Fillet = new javax.swing.JTextField();
        TxtTeh_Obeng = new javax.swing.JTextField();
        TxtSotong_Tepung = new javax.swing.JTextField();
        TxtLemon_Tea = new javax.swing.JTextField();
        TxtGreentea = new javax.swing.JTextField();
        TxtThai_Tea = new javax.swing.JTextField();
        TxtKentang_Goreng = new javax.swing.JTextField();
        TxtTela_Tela = new javax.swing.JTextField();
        TxtKulit_Ayam = new javax.swing.JTextField();
        TxtGorengan = new javax.swing.JTextField();
        TxtNasi_Goreng = new javax.swing.JTextField();
        TxtSeblak = new javax.swing.JTextField();
        TxtSoto = new javax.swing.JTextField();
        TxtKwitiau = new javax.swing.JTextField();
        Chicken_Fillet = new javax.swing.JCheckBox();
        Lemon_Tea = new javax.swing.JCheckBox();
        Ayam_Penyet = new javax.swing.JCheckBox();
        Ayam_Rica_Rica = new javax.swing.JCheckBox();
        Teh_Obeng = new javax.swing.JCheckBox();
        Sotong_Tepung = new javax.swing.JCheckBox();
        Thai_Tea = new javax.swing.JCheckBox();
        Greentea = new javax.swing.JCheckBox();
        Tela_Tela = new javax.swing.JCheckBox();
        Kulit_Ayam = new javax.swing.JCheckBox();
        Kentang_Goreng = new javax.swing.JCheckBox();
        Gorengan = new javax.swing.JCheckBox();
        Kwitiau = new javax.swing.JCheckBox();
        Soto = new javax.swing.JCheckBox();
        Nasi_Goreng = new javax.swing.JCheckBox();
        Seblak = new javax.swing.JCheckBox();
        label17 = new java.awt.Label();
        B_data = new javax.swing.JButton();

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lkjhg.setEnabled(false);

        label1.setText("Chicken Fillet         Rp.15.000/porsi");

        label2.setText("Nasi Goreng            Rp.10.000/porsi                ");

        label3.setText("Seblak                     Rp.12.000/porsi");

        label4.setText("Kwitiau                      Rp.12.000/porsi                                ");

        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setText("TELA-TELA             Rp.5.000/bks                    ");

        label6.setText("Kulit Ayam               Rp.5.000/bks                    ");

        label7.setText("Kentang Goreng    Rp.7.000/bks                    ");

        label8.setText("Gorengan                Rp.1.000/pcs                    ");

        label9.setText("Lemon Tea              Rp.6.000/gelas                               ");

        label10.setText("Teh Obeng              Rp.4.000/gelas                                ");

        label11.setText("Greentea                  Rp.10.000/gelas                               ");

        label12.setText("Thai Tea                   Rp.8.000/gelas                             ");

        label13.setText("Sotong Tepung      Rp.16.000/porsi                    ");

        label14.setText("Soto+ Nasi              Rp.12.000/porsi    ");

        label15.setText("Ayam Penyet           Rp.15.000/porsi                    ");

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        jLabel1.setText("        Bayar ");

        jLabel2.setText("  Kembalian");

        B_Hapus.setText("HAPUS");
        B_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HapusActionPerformed(evt);
            }
        });

        B_Hitung.setText("HITUNG");
        B_Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HitungActionPerformed(evt);
            }
        });

        hitungkem.setText("KEMBALIAN");
        hitungkem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitungkemMouseClicked(evt);
            }
        });
        hitungkem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungkemActionPerformed(evt);
            }
        });

        B_selesai.setText("SELESAI");
        B_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_selesaiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("MENU TAMBAHAN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PROSES TRANSAKSI");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MENU RINGAN");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MINUMAN");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MENU UTAMA");

        TxtAyam_Penyet.setEnabled(false);
        TxtAyam_Penyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAyam_PenyetActionPerformed(evt);
            }
        });

        TxtAyam_Rica_Rica.setEnabled(false);
        TxtAyam_Rica_Rica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAyam_Rica_RicaActionPerformed(evt);
            }
        });

        TxtChicken_Fillet.setEnabled(false);
        TxtChicken_Fillet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtChicken_FilletActionPerformed(evt);
            }
        });

        TxtTeh_Obeng.setEnabled(false);
        TxtTeh_Obeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTeh_ObengActionPerformed(evt);
            }
        });

        TxtSotong_Tepung.setEnabled(false);
        TxtSotong_Tepung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSotong_TepungActionPerformed(evt);
            }
        });

        TxtLemon_Tea.setEnabled(false);
        TxtLemon_Tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLemon_TeaActionPerformed(evt);
            }
        });

        TxtGreentea.setEnabled(false);
        TxtGreentea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGreenteaActionPerformed(evt);
            }
        });

        TxtThai_Tea.setEnabled(false);
        TxtThai_Tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtThai_TeaActionPerformed(evt);
            }
        });

        TxtKentang_Goreng.setEnabled(false);
        TxtKentang_Goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKentang_GorengActionPerformed(evt);
            }
        });

        TxtTela_Tela.setEnabled(false);
        TxtTela_Tela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTela_TelaActionPerformed(evt);
            }
        });

        TxtKulit_Ayam.setEnabled(false);
        TxtKulit_Ayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKulit_AyamActionPerformed(evt);
            }
        });

        TxtGorengan.setEnabled(false);
        TxtGorengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGorenganActionPerformed(evt);
            }
        });

        TxtNasi_Goreng.setEnabled(false);
        TxtNasi_Goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNasi_GorengActionPerformed(evt);
            }
        });

        TxtSeblak.setEnabled(false);
        TxtSeblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSeblakActionPerformed(evt);
            }
        });

        TxtSoto.setEnabled(false);
        TxtSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSotoActionPerformed(evt);
            }
        });

        TxtKwitiau.setEnabled(false);
        TxtKwitiau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKwitiauActionPerformed(evt);
            }
        });

        Chicken_Fillet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chicken_FilletActionPerformed(evt);
            }
        });

        Lemon_Tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lemon_TeaActionPerformed(evt);
            }
        });

        Ayam_Penyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayam_PenyetActionPerformed(evt);
            }
        });

        Ayam_Rica_Rica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayam_Rica_RicaActionPerformed(evt);
            }
        });

        Teh_Obeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teh_ObengActionPerformed(evt);
            }
        });

        Sotong_Tepung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sotong_TepungActionPerformed(evt);
            }
        });

        Thai_Tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thai_TeaActionPerformed(evt);
            }
        });

        Greentea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenteaActionPerformed(evt);
            }
        });

        Tela_Tela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tela_TelaActionPerformed(evt);
            }
        });

        Kulit_Ayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kulit_AyamActionPerformed(evt);
            }
        });

        Kentang_Goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kentang_GorengActionPerformed(evt);
            }
        });

        Gorengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GorenganActionPerformed(evt);
            }
        });

        Kwitiau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KwitiauActionPerformed(evt);
            }
        });

        Soto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SotoActionPerformed(evt);
            }
        });

        Nasi_Goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nasi_GorengActionPerformed(evt);
            }
        });

        Seblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeblakActionPerformed(evt);
            }
        });

        label17.setText("Ayam Rica-Rica     Rp.14.000/porsi");

        B_data.setText("LIHAT DATA");
        B_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lkjhgLayout = new javax.swing.GroupLayout(lkjhg);
        lkjhg.setLayout(lkjhgLayout);
        lkjhgLayout.setHorizontalGroup(
            lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lkjhgLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(540, 540, 540))
            .addGroup(lkjhgLayout.createSequentialGroup()
                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lkjhgLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Thai_Tea)
                                    .addComponent(Greentea))
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addComponent(Sotong_Tepung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addComponent(Ayam_Rica_Rica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addComponent(Ayam_Penyet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addComponent(Teh_Obeng)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addComponent(Chicken_Fillet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addComponent(Lemon_Tea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(lkjhgLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lkjhgLayout.createSequentialGroup()
                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lkjhgLayout.createSequentialGroup()
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addComponent(TxtTeh_Obeng, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(322, 322, 322)
                                        .addComponent(B_Hitung))
                                    .addComponent(TxtAyam_Penyet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addComponent(B_Hapus)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(251, 251, 251))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Seblak, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                                        .addComponent(Soto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                                        .addComponent(Nasi_Goreng, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                                        .addComponent(Kwitiau, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                                        .addGap(31, 31, 31)
                                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addComponent(TxtLemon_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addComponent(TxtGreentea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                                    .addComponent(hitungkem)
                                                    .addGap(160, 160, 160)))
                                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(146, 146, 146)))
                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtSeblak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtKwitiau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNasi_Goreng, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60))
                    .addGroup(lkjhgLayout.createSequentialGroup()
                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                        .addComponent(TxtChicken_Fillet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addComponent(Tela_Tela)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtSotong_Tepung, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtAyam_Rica_Rica, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(95, 95, 95)
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addComponent(Kentang_Goreng)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addComponent(Gorengan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addComponent(Kulit_Ayam)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(TxtTela_Tela, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtKentang_Goreng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtKulit_Ayam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtGorengan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(TxtThai_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_selesai)
                .addGap(18, 18, 18)
                .addComponent(B_data)
                .addGap(328, 328, 328))
        );
        lkjhgLayout.setVerticalGroup(
            lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lkjhgLayout.createSequentialGroup()
                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lkjhgLayout.createSequentialGroup()
                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtChicken_Fillet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tela_Tela)))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTela_Tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lkjhgLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtSeblak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Sotong_Tepung)
                                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TxtSotong_Tepung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TxtKentang_Goreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(TxtKulit_Ayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtGorengan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(lkjhgLayout.createSequentialGroup()
                                                    .addGap(44, 44, 44)
                                                    .addComponent(TxtAyam_Penyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lkjhgLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(TxtAyam_Rica_Rica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Ayam_Rica_Rica))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Ayam_Penyet)))))
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(B_Hapus)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TxtLemon_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Lemon_Tea)
                                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel6))
                                                        .addGap(5, 5, 5)
                                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(Teh_Obeng)
                                                                    .addComponent(TxtTeh_Obeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(B_Hitung)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(1, 1, 1)))
                                        .addGap(10, 10, 10))
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Kentang_Goreng))
                                        .addGap(18, 18, Short.MAX_VALUE)))
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addComponent(Thai_Tea)
                                        .addGap(10, 10, 10)
                                        .addComponent(Greentea))
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addComponent(TxtThai_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(TxtGreentea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hitungkem))))))
                            .addGroup(lkjhgLayout.createSequentialGroup()
                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(lkjhgLayout.createSequentialGroup()
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addComponent(Chicken_Fillet)
                                                .addGap(45, 45, 45)
                                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Kulit_Ayam)
                                                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(lkjhgLayout.createSequentialGroup()
                                                .addComponent(Seblak)
                                                .addGap(11, 11, 11)
                                                .addComponent(Soto)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Nasi_Goreng)
                                                    .addComponent(TxtNasi_Goreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Gorengan)
                                                    .addComponent(label8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(TxtKwitiau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(lkjhgLayout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(Kwitiau))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(lkjhgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_selesai)
                    .addComponent(B_data))
                .addGap(185, 185, 185))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lkjhg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lkjhg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtAyam_PenyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAyam_PenyetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtAyam_PenyetActionPerformed

    private void TxtChicken_FilletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtChicken_FilletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtChicken_FilletActionPerformed

    private void TxtTeh_ObengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTeh_ObengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTeh_ObengActionPerformed

    private void TxtSotong_TepungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSotong_TepungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSotong_TepungActionPerformed

    private void TxtLemon_TeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLemon_TeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLemon_TeaActionPerformed

    private void TxtGreenteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGreenteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGreenteaActionPerformed

    private void TxtThai_TeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtThai_TeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtThai_TeaActionPerformed

    private void TxtKentang_GorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKentang_GorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKentang_GorengActionPerformed

    private void TxtTela_TelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTela_TelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTela_TelaActionPerformed

    private void TxtKulit_AyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKulit_AyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKulit_AyamActionPerformed

    private void TxtGorenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGorenganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGorenganActionPerformed

    private void TxtNasi_GorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNasi_GorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNasi_GorengActionPerformed

    private void TxtSeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSeblakActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtSeblakActionPerformed

    private void TxtSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSotoActionPerformed

    private void TxtKwitiauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKwitiauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKwitiauActionPerformed
         
    private void TxtAyam_Rica_RicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAyam_Rica_RicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAyam_Rica_RicaActionPerformed

    private void Chicken_FilletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chicken_FilletActionPerformed
        // TODO add your handling code here:
         if(Chicken_Fillet.isSelected()){
         TxtChicken_Fillet.setEnabled(true);
      
         }else{TxtChicken_Fillet.setEnabled(false);
         TxtChicken_Fillet.setText("");}
    }//GEN-LAST:event_Chicken_FilletActionPerformed

    private void Lemon_TeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lemon_TeaActionPerformed
        // TODO add your handling code here:
        if(Lemon_Tea.isSelected()==true){
         TxtLemon_Tea.setEnabled(true);
         }else{TxtLemon_Tea.setEnabled(false);
         TxtLemon_Tea.setText("");}
    }//GEN-LAST:event_Lemon_TeaActionPerformed

    private void Ayam_PenyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayam_PenyetActionPerformed
        // TODO add your handling code here:
         if(Ayam_Penyet.isSelected()==true){
         TxtAyam_Penyet.setEnabled(true);
         }else{TxtAyam_Penyet.setEnabled(false);
         TxtAyam_Penyet.setText("");}
    }//GEN-LAST:event_Ayam_PenyetActionPerformed

    private void Ayam_Rica_RicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayam_Rica_RicaActionPerformed
        // TODO add your handling code here:
         if(Ayam_Rica_Rica.isSelected()==true){
         TxtAyam_Rica_Rica.setEnabled(true);
         }else{TxtAyam_Rica_Rica.setEnabled(false);
         TxtAyam_Rica_Rica.setText("");} 
    }//GEN-LAST:event_Ayam_Rica_RicaActionPerformed

    private void Teh_ObengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teh_ObengActionPerformed
        // TODO add your handling code here:
        if(Teh_Obeng.isSelected()==true){
         TxtTeh_Obeng.setEnabled(true);
         }else{TxtTeh_Obeng.setEnabled(false);
         TxtTeh_Obeng.setText("");}  
    }//GEN-LAST:event_Teh_ObengActionPerformed

    private void Sotong_TepungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sotong_TepungActionPerformed
        // TODO add your handling code here:
        if(Sotong_Tepung.isSelected()==true){
         TxtSotong_Tepung.setEnabled(true);
         }else{TxtSotong_Tepung.setEnabled(false);
         TxtSotong_Tepung.setText("");} 
    }//GEN-LAST:event_Sotong_TepungActionPerformed

    private void Thai_TeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thai_TeaActionPerformed
        // TODO add your handling code here:
        if(Thai_Tea.isSelected()==true){
         TxtThai_Tea.setEnabled(true);
         }else{TxtThai_Tea.setEnabled(false);
         TxtThai_Tea.setText("");} 
    }//GEN-LAST:event_Thai_TeaActionPerformed

    private void GreenteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenteaActionPerformed
        // TODO add your handling code here:
       if(Greentea.isSelected()==true){
         TxtGreentea.setEnabled(true);
         }else{TxtGreentea.setEnabled(false);
         TxtGreentea.setText("");}  
    }//GEN-LAST:event_GreenteaActionPerformed

    private void Tela_TelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tela_TelaActionPerformed
        // TODO add your handling code here:
        if(Tela_Tela.isSelected()){
         TxtTela_Tela.setEnabled(true);
         }else{TxtTela_Tela.setEnabled(false);
         TxtTela_Tela.setText("");}
    }//GEN-LAST:event_Tela_TelaActionPerformed

    private void Kulit_AyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kulit_AyamActionPerformed
        // TODO add your handling code here:
        if(Kulit_Ayam.isSelected()){
         TxtKulit_Ayam.setEnabled(true);
         }else{TxtKulit_Ayam.setEnabled(false);
         TxtKulit_Ayam.setText("");}
    }//GEN-LAST:event_Kulit_AyamActionPerformed

    private void Kentang_GorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kentang_GorengActionPerformed
        // TODO add your handling code here:
       if(Kentang_Goreng.isSelected()==true){
         TxtKentang_Goreng.setEnabled(true);
         }else{TxtKentang_Goreng.setEnabled(false);
         TxtKentang_Goreng.setText("");}
    }//GEN-LAST:event_Kentang_GorengActionPerformed

    private void GorenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GorenganActionPerformed
        // TODO add your handling code here:
       if(Gorengan.isSelected()==true){
         TxtGorengan.setEnabled(true);
         }else{TxtGorengan.setEnabled(false);
         TxtGorengan.setText("");}
    }//GEN-LAST:event_GorenganActionPerformed

    private void KwitiauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KwitiauActionPerformed
        // TODO add your handling code here:
       if(Kwitiau.isSelected()==true){
         TxtKwitiau.setEnabled(true);
         }else{TxtKwitiau.setEnabled(false);
         TxtKwitiau.setText("");}
    }//GEN-LAST:event_KwitiauActionPerformed

    private void SotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SotoActionPerformed
        // TODO add your handling code here:
       if(Soto.isSelected()==true){
         TxtSoto.setEnabled(true);
         }else{TxtSoto.setEnabled(false);
         TxtSoto.setText("");}
    }//GEN-LAST:event_SotoActionPerformed

    private void Nasi_GorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nasi_GorengActionPerformed
        // TODO add your handling code here:
       if(Nasi_Goreng.isSelected()==true){
         TxtNasi_Goreng.setEnabled(true);
         }else{TxtNasi_Goreng.setEnabled(false);
         TxtNasi_Goreng.setText("");}
    }//GEN-LAST:event_Nasi_GorengActionPerformed

    private void SeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeblakActionPerformed
        // TODO add your handling code here:
        if(Seblak.isSelected()==true){
         TxtSeblak.setEnabled(true);
         }else{TxtSeblak.setEnabled(false);
         TxtSeblak.setText("");}
    }//GEN-LAST:event_SeblakActionPerformed

    private void B_HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HitungActionPerformed
        // TODO add your handling code here:
        
        if(Chicken_Fillet.isSelected()){
            String chicken = TxtChicken_Fillet.getText();
            int jumlahchicken=Integer.parseInt(chicken);
            int hargachicken=jumlahchicken*15000;
            total = total+hargachicken;
            makan+="Chicken Fillet, ";
            jml+=jumlahchicken;
        }
        
        if(Sotong_Tepung.isSelected()){
            String sotong = TxtSotong_Tepung.getText();
            int jumlahsotong=Integer.parseInt(sotong);
            int hargasotong=jumlahsotong*16000;
            total = total+hargasotong;
            makan+="Sotong Tepung, ";
            jml+=jumlahsotong;
        }
        
        if(Ayam_Rica_Rica.isSelected()){
            String rica = TxtAyam_Rica_Rica.getText();
            int jumlahrica=Integer.parseInt(rica);
            int hargarica=jumlahrica*14000;
            total = total+hargarica;
            makan+="Ayam Rica rica, ";
            jml+=jumlahrica;
        }
        
        if(Ayam_Penyet.isSelected()){
            String penyet = TxtAyam_Penyet.getText();
            int jumlahpenyet=Integer.parseInt(penyet);
            int hargapenyet=jumlahpenyet*15000;
            total = total + hargapenyet;
            makan+="Ayam Penyet, ";
            jml+=jumlahpenyet;
        }
        
        if(Tela_Tela.isSelected()){
            String tela = TxtTela_Tela.getText();
            int jumlahtela=Integer.parseInt(tela);
            int hargatela=jumlahtela*5000;
            total = total + hargatela;
            makan+="Tela tela, ";
            jml+=jumlahtela;
        }
        
         if(Kentang_Goreng.isSelected()){
            String kentang = TxtKentang_Goreng.getText();
            int jumlahkentang=Integer.parseInt(kentang);
            int hargakentang=jumlahkentang*7000;
            total = total + hargakentang;
            makan+="Kentang Goreng, ";
            jml+=jumlahkentang;
        }
         
         if(Kulit_Ayam.isSelected()){
            String kulit = TxtKulit_Ayam.getText();
            int jumlahkulit=Integer.parseInt(kulit);
            int hargakulit=jumlahkulit*5000;
            total = total + hargakulit;
            makan+="Kulit Ayam, ";
            jml+=jumlahkulit;
         }
         
         if(Gorengan.isSelected()){
            String gorengan = TxtGorengan.getText();
            int jumlahgorengan=Integer.parseInt(gorengan);
            int hargagorengan=jumlahgorengan*1000;
            total = total + hargagorengan;
            makan+="Gorengan, ";
            jml+=jumlahgorengan;
         } 
         
         if(Seblak.isSelected()){
            String seblak = TxtSeblak.getText();
            int jumlahseblak=Integer.parseInt(seblak);
            int hargaseblak=jumlahseblak*12000;
            total = total + hargaseblak;
            makan+="Seblak, ";
            jml+=jumlahseblak;
         } 
         
         if(Soto.isSelected()){
            String soto = TxtSoto.getText();
            int jumlahsoto=Integer.parseInt(soto);
            int hargasoto=jumlahsoto*12000;
            total = total + hargasoto;
            makan+="Soto, ";
            jml+=jumlahsoto;
         } 
         
        if(Nasi_Goreng.isSelected()){
            String nasi_goreng = TxtNasi_Goreng.getText();
            int jumlahnasi_goreng=Integer.parseInt(nasi_goreng);
            int harganasi_goreng=jumlahnasi_goreng*10000;
            total = total + harganasi_goreng;
            makan+="Nasi Goreng, ";
            jml+=jumlahnasi_goreng;
        } 
        
        if(Kwitiau.isSelected()){
            String kwitiau = TxtKwitiau.getText();
            int jumlahkwitiau=Integer.parseInt(kwitiau);
            int hargakwitiau=jumlahkwitiau*12000;
            total = total + hargakwitiau;
            makan+="Kwitiau, ";
            jml+=jumlahkwitiau;
        }
         
        if(Teh_Obeng.isSelected()){
            String teh_obeng = TxtTeh_Obeng.getText();
            int jumlahteh_obeng=Integer.parseInt(teh_obeng);
            int hargateh_obeng=jumlahteh_obeng*4000;
            total = total + hargateh_obeng;
            makan+="Teh Obeng, ";
            jml+=jumlahteh_obeng;
        } 
        
        if(Lemon_Tea.isSelected()){
            String lemon_tea = TxtLemon_Tea.getText();
            int jumlahlemon_tea=Integer.parseInt(lemon_tea);
            int hargalemon_tea=jumlahlemon_tea*6000;
            total = total + hargalemon_tea;
            makan+="Lemon Tea, ";
            jml+=jumlahlemon_tea;
        } 
         
        if(Thai_Tea.isSelected()){
            String thai_tea = TxtThai_Tea.getText();
            int jumlahthai_tea=Integer.parseInt(thai_tea);
            int hargathai_tea=jumlahthai_tea*8000;
            total = total + hargathai_tea;
            makan+="Thai Tea, ";
            jml+=jumlahthai_tea;
        }
        
        if(Greentea.isSelected()){
            String greentea = TxtGreentea.getText();
            int jumlahgreentea=Integer.parseInt(greentea);
            int hargagreentea=jumlahgreentea*10000;
            total = total + hargagreentea;
            makan+="Greentea, ";
            jml+=jumlahgreentea;
        }
        this.total = total; 
        totalharga.setText("Rp. "+total);
         
        //JOptionPane.showMessageDialog(null,makan);
        
    }//GEN-LAST:event_B_HitungActionPerformed

    private void B_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HapusActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_B_HapusActionPerformed

    private void hitungkemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungkemActionPerformed
        // TODO add your handling code here:
        a= Integer.parseInt(bayar.getText());
        h= (a-total);
        
        if(h>=0){
            kembalian.setText(String.valueOf(h));
            tambah(makan,jml, total);
            clear();
        }else{
            JOptionPane.showMessageDialog(null,"Uang anda tidak cukup");
        }
    }//GEN-LAST:event_hitungkemActionPerformed

    private void B_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_selesaiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_B_selesaiActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void hitungkemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungkemMouseClicked
        // TODO add your handling code here
        
    }//GEN-LAST:event_hitungkemMouseClicked

    private void B_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_dataActionPerformed
        // TODO add your handling code here:
        Data data = new Data();
        data.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ayam_Penyet;
    private javax.swing.JCheckBox Ayam_Rica_Rica;
    private javax.swing.JButton B_Hapus;
    private javax.swing.JButton B_Hitung;
    private javax.swing.JButton B_data;
    private javax.swing.JButton B_selesai;
    private javax.swing.JCheckBox Chicken_Fillet;
    private javax.swing.JCheckBox Gorengan;
    private javax.swing.JCheckBox Greentea;
    private javax.swing.JCheckBox Kentang_Goreng;
    private javax.swing.JCheckBox Kulit_Ayam;
    private javax.swing.JCheckBox Kwitiau;
    private javax.swing.JCheckBox Lemon_Tea;
    private javax.swing.JCheckBox Nasi_Goreng;
    private javax.swing.JCheckBox Seblak;
    private javax.swing.JCheckBox Soto;
    private javax.swing.JCheckBox Sotong_Tepung;
    private javax.swing.JCheckBox Teh_Obeng;
    private javax.swing.JCheckBox Tela_Tela;
    private javax.swing.JCheckBox Thai_Tea;
    private javax.swing.JTextField TxtAyam_Penyet;
    private javax.swing.JTextField TxtAyam_Rica_Rica;
    private javax.swing.JTextField TxtChicken_Fillet;
    private javax.swing.JTextField TxtGorengan;
    private javax.swing.JTextField TxtGreentea;
    private javax.swing.JTextField TxtKentang_Goreng;
    private javax.swing.JTextField TxtKulit_Ayam;
    private javax.swing.JTextField TxtKwitiau;
    private javax.swing.JTextField TxtLemon_Tea;
    private javax.swing.JTextField TxtNasi_Goreng;
    private javax.swing.JTextField TxtSeblak;
    private javax.swing.JTextField TxtSoto;
    private javax.swing.JTextField TxtSotong_Tepung;
    private javax.swing.JTextField TxtTeh_Obeng;
    private javax.swing.JTextField TxtTela_Tela;
    private javax.swing.JTextField TxtThai_Tea;
    private IF2A.Background background2;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton hitungkem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kembalian;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label17;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private IF2A.Background lkjhg;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables
}
